// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ApprovalResolveRequestResolution.
const (
	AllowAlways       ApprovalResolveRequestResolution = "allow-always"
	AllowCurrentChain ApprovalResolveRequestResolution = "allow-current-chain"
	AllowOnce         ApprovalResolveRequestResolution = "allow-once"
	Approved          ApprovalResolveRequestResolution = "approved"
	Blocked           ApprovalResolveRequestResolution = "blocked"
	Denied            ApprovalResolveRequestResolution = "denied"
	Failed            ApprovalResolveRequestResolution = "failed"
	Rejected          ApprovalResolveRequestResolution = "rejected"
)

// Valid indicates whether the value is a known member of the ApprovalResolveRequestResolution enum.
func (e ApprovalResolveRequestResolution) Valid() bool {
	switch e {
	case AllowAlways:
		return true
	case AllowCurrentChain:
		return true
	case AllowOnce:
		return true
	case Approved:
		return true
	case Blocked:
		return true
	case Denied:
		return true
	case Failed:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalResolveRequestRiskLevel.
const (
	L0 ApprovalResolveRequestRiskLevel = "L0"
	L1 ApprovalResolveRequestRiskLevel = "L1"
	L2 ApprovalResolveRequestRiskLevel = "L2"
	L3 ApprovalResolveRequestRiskLevel = "L3"
	L4 ApprovalResolveRequestRiskLevel = "L4"
)

// Valid indicates whether the value is a known member of the ApprovalResolveRequestRiskLevel enum.
func (e ApprovalResolveRequestRiskLevel) Valid() bool {
	switch e {
	case L0:
		return true
	case L1:
		return true
	case L2:
		return true
	case L3:
		return true
	case L4:
		return true
	default:
		return false
	}
}

// Defines values for CapabilitiesResponseQueryApiVersion.
const (
	V1 CapabilitiesResponseQueryApiVersion = "v1"
)

// Valid indicates whether the value is a known member of the CapabilitiesResponseQueryApiVersion enum.
func (e CapabilitiesResponseQueryApiVersion) Valid() bool {
	switch e {
	case V1:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseOk.
const (
	False ErrorResponseOk = false
)

// Valid indicates whether the value is a known member of the ErrorResponseOk enum.
func (e ErrorResponseOk) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseSchemaVersion.
const (
	HealthResponseSchemaVersionLynxServerIngestV1 HealthResponseSchemaVersion = "lynx-server.ingest.v1"
)

// Valid indicates whether the value is a known member of the HealthResponseSchemaVersion enum.
func (e HealthResponseSchemaVersion) Valid() bool {
	switch e {
	case HealthResponseSchemaVersionLynxServerIngestV1:
		return true
	default:
		return false
	}
}

// Defines values for IngestBatchRequestSchemaVersion.
const (
	IngestBatchRequestSchemaVersionLynxServerIngestV1 IngestBatchRequestSchemaVersion = "lynx-server.ingest.v1"
)

// Valid indicates whether the value is a known member of the IngestBatchRequestSchemaVersion enum.
func (e IngestBatchRequestSchemaVersion) Valid() bool {
	switch e {
	case IngestBatchRequestSchemaVersionLynxServerIngestV1:
		return true
	default:
		return false
	}
}

// Defines values for IngestItemKind.
const (
	ApprovalUpsert  IngestItemKind = "approvalUpsert"
	AuditEvent      IngestItemKind = "auditEvent"
	LynxCheckUpsert IngestItemKind = "lynxCheckUpsert"
	SessionUpsert   IngestItemKind = "sessionUpsert"
	TokenUsage      IngestItemKind = "tokenUsage"
	ToolCallUpsert  IngestItemKind = "toolCallUpsert"
)

// Valid indicates whether the value is a known member of the IngestItemKind enum.
func (e IngestItemKind) Valid() bool {
	switch e {
	case ApprovalUpsert:
		return true
	case AuditEvent:
		return true
	case LynxCheckUpsert:
		return true
	case SessionUpsert:
		return true
	case TokenUsage:
		return true
	case ToolCallUpsert:
		return true
	default:
		return false
	}
}

// Defines values for GetTokenTrendParamsBucket.
const (
	Day    GetTokenTrendParamsBucket = "day"
	Hour   GetTokenTrendParamsBucket = "hour"
	Minute GetTokenTrendParamsBucket = "minute"
)

// Valid indicates whether the value is a known member of the GetTokenTrendParamsBucket enum.
func (e GetTokenTrendParamsBucket) Valid() bool {
	switch e {
	case Day:
		return true
	case Hour:
		return true
	case Minute:
		return true
	default:
		return false
	}
}

// ApprovalResolveRequest defines model for ApprovalResolveRequest.
type ApprovalResolveRequest struct {
	ApprovalId           *string                           `json:"approvalId,omitempty"`
	ApproverId           *string                           `json:"approverId,omitempty"`
	ApproverOuId         *string                           `json:"approverOuId,omitempty"`
	ChainId              *string                           `json:"chainId,omitempty"`
	ChannelId            *string                           `json:"channelId,omitempty"`
	ChannelProfile       *string                           `json:"channelProfile,omitempty"`
	ConversationId       *string                           `json:"conversationId,omitempty"`
	ExpiresAt            *string                           `json:"expiresAt,omitempty"`
	RequesterId          *string                           `json:"requesterId,omitempty"`
	RequesterOuId        *string                           `json:"requesterOuId,omitempty"`
	Resolution           *ApprovalResolveRequestResolution `json:"resolution,omitempty"`
	ResourceScope        *JsonObject                       `json:"resourceScope,omitempty"`
	RiskFamily           *string                           `json:"riskFamily,omitempty"`
	RiskLevel            *ApprovalResolveRequestRiskLevel  `json:"riskLevel,omitempty"`
	SessionKey           *string                           `json:"sessionKey,omitempty"`
	TargetHash           *string                           `json:"targetHash,omitempty"`
	TargetKind           *string                           `json:"targetKind,omitempty"`
	ToolName             *string                           `json:"toolName,omitempty"`
	AdditionalProperties map[string]interface{}            `json:"-"`
}

// ApprovalResolveRequestResolution defines model for ApprovalResolveRequest.Resolution.
type ApprovalResolveRequestResolution string

// ApprovalResolveRequestRiskLevel defines model for ApprovalResolveRequest.RiskLevel.
type ApprovalResolveRequestRiskLevel string

// CapabilitiesResponse defines model for CapabilitiesResponse.
type CapabilitiesResponse struct {
	GatewayAuthLogsEnabled bool                                `json:"gatewayAuthLogsEnabled"`
	QueryApiVersion        CapabilitiesResponseQueryApiVersion `json:"queryApiVersion"`
	TokenUsageEnabled      bool                                `json:"tokenUsageEnabled"`
}

// CapabilitiesResponseQueryApiVersion defines model for CapabilitiesResponse.QueryApiVersion.
type CapabilitiesResponseQueryApiVersion string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string          `json:"message"`
	Ok      ErrorResponseOk `json:"ok"`
}

// ErrorResponseOk defines model for ErrorResponse.Ok.
type ErrorResponseOk bool

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Ok            bool                        `json:"ok"`
	SchemaVersion HealthResponseSchemaVersion `json:"schemaVersion"`
	ServerTimeMs  int64                       `json:"serverTimeMs"`
}

// HealthResponseSchemaVersion defines model for HealthResponse.SchemaVersion.
type HealthResponseSchemaVersion string

// IngestBatchRequest defines model for IngestBatchRequest.
type IngestBatchRequest struct {
	BatchId              string                          `json:"batchId"`
	Items                []IngestItem                    `json:"items"`
	Producer             IngestBatchRequest_Producer     `json:"producer"`
	SchemaVersion        IngestBatchRequestSchemaVersion `json:"schemaVersion"`
	SentAtMs             int64                           `json:"sentAtMs"`
	AdditionalProperties map[string]interface{}          `json:"-"`
}

// IngestBatchRequest_Producer defines model for IngestBatchRequest.Producer.
type IngestBatchRequest_Producer struct {
	PluginId             string                 `json:"pluginId"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// IngestBatchRequestSchemaVersion defines model for IngestBatchRequest.SchemaVersion.
type IngestBatchRequestSchemaVersion string

// IngestBatchResponse defines model for IngestBatchResponse.
type IngestBatchResponse struct {
	AcceptedCount        int                    `json:"acceptedCount"`
	DuplicateCount       int                    `json:"duplicateCount"`
	PersistedCount       int                    `json:"persistedCount"`
	RejectedCount        int                    `json:"rejectedCount"`
	RejectedItems        *[]JsonObject          `json:"rejectedItems,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// IngestItem defines model for IngestItem.
type IngestItem struct {
	Data                 JsonObject             `json:"data"`
	ItemId               string                 `json:"itemId"`
	Kind                 IngestItemKind         `json:"kind"`
	OccurredAtMs         int64                  `json:"occurredAtMs"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// IngestItemKind defines model for IngestItem.Kind.
type IngestItemKind string

// JsonObject defines model for JsonObject.
type JsonObject map[string]interface{}

// Page defines model for Page.
type Page struct {
	Items                []JsonObject           `json:"items"`
	NextCursor           *string                `json:"nextCursor,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ApprovalId defines model for ApprovalId.
type ApprovalId = string

// Category defines model for Category.
type Category = string

// Cursor defines model for Cursor.
type Cursor = string

// Direction defines model for Direction.
type Direction = string

// EnforcementAction defines model for EnforcementAction.
type EnforcementAction = []string

// EventType defines model for EventType.
type EventType = string

// FromMs defines model for FromMs.
type FromMs = int64

// HookName defines model for HookName.
type HookName = string

// Limit defines model for Limit.
type Limit = int

// PrimaryModule defines model for PrimaryModule.
type PrimaryModule = string

// Q defines model for Q.
type Q = string

// RequestId defines model for RequestId.
type RequestId = string

// RiskLevel defines model for RiskLevel.
type RiskLevel = []string

// RunId defines model for RunId.
type RunId = string

// SessionKey defines model for SessionKey.
type SessionKey = string

// SubCategory defines model for SubCategory.
type SubCategory = string

// ToMs defines model for ToMs.
type ToMs = int64

// ToolCallId defines model for ToolCallId.
type ToolCallId = string

// ToolName defines model for ToolName.
type ToolName = string

// IngestBatchResult defines model for IngestBatchResult.
type IngestBatchResult = IngestBatchResponse

// ObjectResponse defines model for ObjectResponse.
type ObjectResponse = JsonObject

// PageResponse defines model for PageResponse.
type PageResponse = Page

// IngestBatchRequestBody defines model for IngestBatchRequestBody.
type IngestBatchRequestBody = IngestBatchRequest

// ListApprovalsParams defines parameters for ListApprovals.
type ListApprovalsParams struct {
	FromMs        *FromMs     `form:"fromMs,omitempty" json:"fromMs,omitempty"`
	ToMs          *ToMs       `form:"toMs,omitempty" json:"toMs,omitempty"`
	SessionKey    *SessionKey `form:"sessionKey,omitempty" json:"sessionKey,omitempty"`
	RunId         *RunId      `form:"runId,omitempty" json:"runId,omitempty"`
	RiskLevel     *RiskLevel  `form:"riskLevel,omitempty" json:"riskLevel,omitempty"`
	Limit         *Limit      `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor        *Cursor     `form:"cursor,omitempty" json:"cursor,omitempty"`
	Resolution    *string     `form:"resolution,omitempty" json:"resolution,omitempty"`
	ToolName      *ToolName   `form:"toolName,omitempty" json:"toolName,omitempty"`
	Module        *string     `form:"module,omitempty" json:"module,omitempty"`
	ScopeType     *string     `form:"scopeType,omitempty" json:"scopeType,omitempty"`
	RequesterOuId *string     `form:"requesterOuId,omitempty" json:"requesterOuId,omitempty"`
}

// GetDashboardOverviewParams defines parameters for GetDashboardOverview.
type GetDashboardOverviewParams struct {
	FromMs *FromMs `form:"fromMs,omitempty" json:"fromMs,omitempty"`
	ToMs   *ToMs   `form:"toMs,omitempty" json:"toMs,omitempty"`
}

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	Q                       *Q                 `form:"q,omitempty" json:"q,omitempty"`
	FromMs                  *FromMs            `form:"fromMs,omitempty" json:"fromMs,omitempty"`
	ToMs                    *ToMs              `form:"toMs,omitempty" json:"toMs,omitempty"`
	SessionKey              *SessionKey        `form:"sessionKey,omitempty" json:"sessionKey,omitempty"`
	RunId                   *RunId             `form:"runId,omitempty" json:"runId,omitempty"`
	RiskLevel               *RiskLevel         `form:"riskLevel,omitempty" json:"riskLevel,omitempty"`
	EnforcementAction       *EnforcementAction `form:"enforcementAction,omitempty" json:"enforcementAction,omitempty"`
	Limit                   *Limit             `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor                  *Cursor            `form:"cursor,omitempty" json:"cursor,omitempty"`
	HookName                *HookName          `form:"hookName,omitempty" json:"hookName,omitempty"`
	EventType               *EventType         `form:"eventType,omitempty" json:"eventType,omitempty"`
	Category                *Category          `form:"category,omitempty" json:"category,omitempty"`
	SubCategory             *SubCategory       `form:"subCategory,omitempty" json:"subCategory,omitempty"`
	Direction               *Direction         `form:"direction,omitempty" json:"direction,omitempty"`
	PrimaryModule           *PrimaryModule     `form:"primaryModule,omitempty" json:"primaryModule,omitempty"`
	RequestId               *RequestId         `form:"requestId,omitempty" json:"requestId,omitempty"`
	ToolCallId              *ToolCallId        `form:"toolCallId,omitempty" json:"toolCallId,omitempty"`
	ApprovalId              *ApprovalId        `form:"approvalId,omitempty" json:"approvalId,omitempty"`
	IncludeRoutineHeartbeat *bool              `form:"includeRoutineHeartbeat,omitempty" json:"includeRoutineHeartbeat,omitempty"`
}

// ListGrantsParams defines parameters for ListGrants.
type ListGrantsParams struct {
	Q           *Q      `form:"q,omitempty" json:"q,omitempty"`
	ChainId     *string `form:"chainId,omitempty" json:"chainId,omitempty"`
	RequesterId *string `form:"requesterId,omitempty" json:"requesterId,omitempty"`
	Revoked     *bool   `form:"revoked,omitempty" json:"revoked,omitempty"`
	PageNum     *int    `form:"pageNum,omitempty" json:"pageNum,omitempty"`
	PageSize    *int    `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	Limit       *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListLynxChecksParams defines parameters for ListLynxChecks.
type ListLynxChecksParams struct {
	Q               *Q          `form:"q,omitempty" json:"q,omitempty"`
	FromMs          *FromMs     `form:"fromMs,omitempty" json:"fromMs,omitempty"`
	ToMs            *ToMs       `form:"toMs,omitempty" json:"toMs,omitempty"`
	SessionKey      *SessionKey `form:"sessionKey,omitempty" json:"sessionKey,omitempty"`
	Limit           *Limit      `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor          *Cursor     `form:"cursor,omitempty" json:"cursor,omitempty"`
	Source          *string     `form:"source,omitempty" json:"source,omitempty"`
	Trigger         *string     `form:"trigger,omitempty" json:"trigger,omitempty"`
	Status          *string     `form:"status,omitempty" json:"status,omitempty"`
	MessageProvider *string     `form:"messageProvider,omitempty" json:"messageProvider,omitempty"`
}

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	FromMs         *FromMs `form:"fromMs,omitempty" json:"fromMs,omitempty"`
	ToMs           *ToMs   `form:"toMs,omitempty" json:"toMs,omitempty"`
	Limit          *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor         *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	ChannelProfile *string `form:"channelProfile,omitempty" json:"channelProfile,omitempty"`
	ChannelId      *string `form:"channelId,omitempty" json:"channelId,omitempty"`
	RequesterId    *string `form:"requesterId,omitempty" json:"requesterId,omitempty"`
	RequesterOuId  *string `form:"requesterOuId,omitempty" json:"requesterOuId,omitempty"`
	IsGroup        *bool   `form:"isGroup,omitempty" json:"isGroup,omitempty"`
}

// GetTokenSummaryParams defines parameters for GetTokenSummary.
type GetTokenSummaryParams struct {
	FromMs     *FromMs     `form:"fromMs,omitempty" json:"fromMs,omitempty"`
	ToMs       *ToMs       `form:"toMs,omitempty" json:"toMs,omitempty"`
	SessionKey *SessionKey `form:"sessionKey,omitempty" json:"sessionKey,omitempty"`
	RunId      *RunId      `form:"runId,omitempty" json:"runId,omitempty"`
	Provider   *string     `form:"provider,omitempty" json:"provider,omitempty"`
	Model      *string     `form:"model,omitempty" json:"model,omitempty"`
}

// GetTokenTrendParams defines parameters for GetTokenTrend.
type GetTokenTrendParams struct {
	FromMs     *FromMs                    `form:"fromMs,omitempty" json:"fromMs,omitempty"`
	ToMs       *ToMs                      `form:"toMs,omitempty" json:"toMs,omitempty"`
	SessionKey *SessionKey                `form:"sessionKey,omitempty" json:"sessionKey,omitempty"`
	RunId      *RunId                     `form:"runId,omitempty" json:"runId,omitempty"`
	Provider   *string                    `form:"provider,omitempty" json:"provider,omitempty"`
	Model      *string                    `form:"model,omitempty" json:"model,omitempty"`
	Bucket     *GetTokenTrendParamsBucket `form:"bucket,omitempty" json:"bucket,omitempty"`
}

// GetTokenTrendParamsBucket defines parameters for GetTokenTrend.
type GetTokenTrendParamsBucket string

// ListTokenUsageParams defines parameters for ListTokenUsage.
type ListTokenUsageParams struct {
	FromMs      *FromMs     `form:"fromMs,omitempty" json:"fromMs,omitempty"`
	ToMs        *ToMs       `form:"toMs,omitempty" json:"toMs,omitempty"`
	SessionKey  *SessionKey `form:"sessionKey,omitempty" json:"sessionKey,omitempty"`
	RunId       *RunId      `form:"runId,omitempty" json:"runId,omitempty"`
	Limit       *Limit      `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor      *Cursor     `form:"cursor,omitempty" json:"cursor,omitempty"`
	Provider    *string     `form:"provider,omitempty" json:"provider,omitempty"`
	Model       *string     `form:"model,omitempty" json:"model,omitempty"`
	AgentId     *string     `form:"agentId,omitempty" json:"agentId,omitempty"`
	IsEstimated *bool       `form:"isEstimated,omitempty" json:"isEstimated,omitempty"`
}

// ListToolCallsParams defines parameters for ListToolCalls.
type ListToolCallsParams struct {
	FromMs            *FromMs            `form:"fromMs,omitempty" json:"fromMs,omitempty"`
	ToMs              *ToMs              `form:"toMs,omitempty" json:"toMs,omitempty"`
	SessionKey        *SessionKey        `form:"sessionKey,omitempty" json:"sessionKey,omitempty"`
	RunId             *RunId             `form:"runId,omitempty" json:"runId,omitempty"`
	RiskLevel         *RiskLevel         `form:"riskLevel,omitempty" json:"riskLevel,omitempty"`
	EnforcementAction *EnforcementAction `form:"enforcementAction,omitempty" json:"enforcementAction,omitempty"`
	Limit             *Limit             `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor            *Cursor            `form:"cursor,omitempty" json:"cursor,omitempty"`
	ToolName          *ToolName          `form:"toolName,omitempty" json:"toolName,omitempty"`
	ResultStatus      *string            `form:"resultStatus,omitempty" json:"resultStatus,omitempty"`
	ApprovalId        *ApprovalId        `form:"approvalId,omitempty" json:"approvalId,omitempty"`
}

// ResolveApprovalJSONRequestBody defines body for ResolveApproval for application/json ContentType.
type ResolveApprovalJSONRequestBody = ApprovalResolveRequest

// IngestApprovalsJSONRequestBody defines body for IngestApprovals for application/json ContentType.
type IngestApprovalsJSONRequestBody = IngestBatchRequest

// IngestAuditEventsJSONRequestBody defines body for IngestAuditEvents for application/json ContentType.
type IngestAuditEventsJSONRequestBody = IngestBatchRequest

// IngestBatchJSONRequestBody defines body for IngestBatch for application/json ContentType.
type IngestBatchJSONRequestBody = IngestBatchRequest

// IngestLynxChecksJSONRequestBody defines body for IngestLynxChecks for application/json ContentType.
type IngestLynxChecksJSONRequestBody = IngestBatchRequest

// IngestSessionsJSONRequestBody defines body for IngestSessions for application/json ContentType.
type IngestSessionsJSONRequestBody = IngestBatchRequest

// IngestTokenUsageJSONRequestBody defines body for IngestTokenUsage for application/json ContentType.
type IngestTokenUsageJSONRequestBody = IngestBatchRequest

// IngestToolCallsJSONRequestBody defines body for IngestToolCalls for application/json ContentType.
type IngestToolCallsJSONRequestBody = IngestBatchRequest

// UpsertPolicyRuleJSONRequestBody defines body for UpsertPolicyRule for application/json ContentType.
type UpsertPolicyRuleJSONRequestBody = JsonObject

// UpsertProtectedResourceJSONRequestBody defines body for UpsertProtectedResource for application/json ContentType.
type UpsertProtectedResourceJSONRequestBody = JsonObject

// Getter for additional properties for ApprovalResolveRequest. Returns the specified
// element and whether it was found
func (a ApprovalResolveRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ApprovalResolveRequest
func (a *ApprovalResolveRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ApprovalResolveRequest to handle AdditionalProperties
func (a *ApprovalResolveRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["approvalId"]; found {
		err = json.Unmarshal(raw, &a.ApprovalId)
		if err != nil {
			return fmt.Errorf("error reading 'approvalId': %w", err)
		}
		delete(object, "approvalId")
	}

	if raw, found := object["approverId"]; found {
		err = json.Unmarshal(raw, &a.ApproverId)
		if err != nil {
			return fmt.Errorf("error reading 'approverId': %w", err)
		}
		delete(object, "approverId")
	}

	if raw, found := object["approverOuId"]; found {
		err = json.Unmarshal(raw, &a.ApproverOuId)
		if err != nil {
			return fmt.Errorf("error reading 'approverOuId': %w", err)
		}
		delete(object, "approverOuId")
	}

	if raw, found := object["chainId"]; found {
		err = json.Unmarshal(raw, &a.ChainId)
		if err != nil {
			return fmt.Errorf("error reading 'chainId': %w", err)
		}
		delete(object, "chainId")
	}

	if raw, found := object["channelId"]; found {
		err = json.Unmarshal(raw, &a.ChannelId)
		if err != nil {
			return fmt.Errorf("error reading 'channelId': %w", err)
		}
		delete(object, "channelId")
	}

	if raw, found := object["channelProfile"]; found {
		err = json.Unmarshal(raw, &a.ChannelProfile)
		if err != nil {
			return fmt.Errorf("error reading 'channelProfile': %w", err)
		}
		delete(object, "channelProfile")
	}

	if raw, found := object["conversationId"]; found {
		err = json.Unmarshal(raw, &a.ConversationId)
		if err != nil {
			return fmt.Errorf("error reading 'conversationId': %w", err)
		}
		delete(object, "conversationId")
	}

	if raw, found := object["expiresAt"]; found {
		err = json.Unmarshal(raw, &a.ExpiresAt)
		if err != nil {
			return fmt.Errorf("error reading 'expiresAt': %w", err)
		}
		delete(object, "expiresAt")
	}

	if raw, found := object["requesterId"]; found {
		err = json.Unmarshal(raw, &a.RequesterId)
		if err != nil {
			return fmt.Errorf("error reading 'requesterId': %w", err)
		}
		delete(object, "requesterId")
	}

	if raw, found := object["requesterOuId"]; found {
		err = json.Unmarshal(raw, &a.RequesterOuId)
		if err != nil {
			return fmt.Errorf("error reading 'requesterOuId': %w", err)
		}
		delete(object, "requesterOuId")
	}

	if raw, found := object["resolution"]; found {
		err = json.Unmarshal(raw, &a.Resolution)
		if err != nil {
			return fmt.Errorf("error reading 'resolution': %w", err)
		}
		delete(object, "resolution")
	}

	if raw, found := object["resourceScope"]; found {
		err = json.Unmarshal(raw, &a.ResourceScope)
		if err != nil {
			return fmt.Errorf("error reading 'resourceScope': %w", err)
		}
		delete(object, "resourceScope")
	}

	if raw, found := object["riskFamily"]; found {
		err = json.Unmarshal(raw, &a.RiskFamily)
		if err != nil {
			return fmt.Errorf("error reading 'riskFamily': %w", err)
		}
		delete(object, "riskFamily")
	}

	if raw, found := object["riskLevel"]; found {
		err = json.Unmarshal(raw, &a.RiskLevel)
		if err != nil {
			return fmt.Errorf("error reading 'riskLevel': %w", err)
		}
		delete(object, "riskLevel")
	}

	if raw, found := object["sessionKey"]; found {
		err = json.Unmarshal(raw, &a.SessionKey)
		if err != nil {
			return fmt.Errorf("error reading 'sessionKey': %w", err)
		}
		delete(object, "sessionKey")
	}

	if raw, found := object["targetHash"]; found {
		err = json.Unmarshal(raw, &a.TargetHash)
		if err != nil {
			return fmt.Errorf("error reading 'targetHash': %w", err)
		}
		delete(object, "targetHash")
	}

	if raw, found := object["targetKind"]; found {
		err = json.Unmarshal(raw, &a.TargetKind)
		if err != nil {
			return fmt.Errorf("error reading 'targetKind': %w", err)
		}
		delete(object, "targetKind")
	}

	if raw, found := object["toolName"]; found {
		err = json.Unmarshal(raw, &a.ToolName)
		if err != nil {
			return fmt.Errorf("error reading 'toolName': %w", err)
		}
		delete(object, "toolName")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ApprovalResolveRequest to handle AdditionalProperties
func (a ApprovalResolveRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ApprovalId != nil {
		object["approvalId"], err = json.Marshal(a.ApprovalId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'approvalId': %w", err)
		}
	}

	if a.ApproverId != nil {
		object["approverId"], err = json.Marshal(a.ApproverId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'approverId': %w", err)
		}
	}

	if a.ApproverOuId != nil {
		object["approverOuId"], err = json.Marshal(a.ApproverOuId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'approverOuId': %w", err)
		}
	}

	if a.ChainId != nil {
		object["chainId"], err = json.Marshal(a.ChainId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'chainId': %w", err)
		}
	}

	if a.ChannelId != nil {
		object["channelId"], err = json.Marshal(a.ChannelId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'channelId': %w", err)
		}
	}

	if a.ChannelProfile != nil {
		object["channelProfile"], err = json.Marshal(a.ChannelProfile)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'channelProfile': %w", err)
		}
	}

	if a.ConversationId != nil {
		object["conversationId"], err = json.Marshal(a.ConversationId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'conversationId': %w", err)
		}
	}

	if a.ExpiresAt != nil {
		object["expiresAt"], err = json.Marshal(a.ExpiresAt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'expiresAt': %w", err)
		}
	}

	if a.RequesterId != nil {
		object["requesterId"], err = json.Marshal(a.RequesterId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'requesterId': %w", err)
		}
	}

	if a.RequesterOuId != nil {
		object["requesterOuId"], err = json.Marshal(a.RequesterOuId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'requesterOuId': %w", err)
		}
	}

	if a.Resolution != nil {
		object["resolution"], err = json.Marshal(a.Resolution)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resolution': %w", err)
		}
	}

	if a.ResourceScope != nil {
		object["resourceScope"], err = json.Marshal(a.ResourceScope)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resourceScope': %w", err)
		}
	}

	if a.RiskFamily != nil {
		object["riskFamily"], err = json.Marshal(a.RiskFamily)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'riskFamily': %w", err)
		}
	}

	if a.RiskLevel != nil {
		object["riskLevel"], err = json.Marshal(a.RiskLevel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'riskLevel': %w", err)
		}
	}

	if a.SessionKey != nil {
		object["sessionKey"], err = json.Marshal(a.SessionKey)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sessionKey': %w", err)
		}
	}

	if a.TargetHash != nil {
		object["targetHash"], err = json.Marshal(a.TargetHash)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'targetHash': %w", err)
		}
	}

	if a.TargetKind != nil {
		object["targetKind"], err = json.Marshal(a.TargetKind)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'targetKind': %w", err)
		}
	}

	if a.ToolName != nil {
		object["toolName"], err = json.Marshal(a.ToolName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'toolName': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for IngestBatchRequest. Returns the specified
// element and whether it was found
func (a IngestBatchRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for IngestBatchRequest
func (a *IngestBatchRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for IngestBatchRequest to handle AdditionalProperties
func (a *IngestBatchRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["batchId"]; found {
		err = json.Unmarshal(raw, &a.BatchId)
		if err != nil {
			return fmt.Errorf("error reading 'batchId': %w", err)
		}
		delete(object, "batchId")
	}

	if raw, found := object["items"]; found {
		err = json.Unmarshal(raw, &a.Items)
		if err != nil {
			return fmt.Errorf("error reading 'items': %w", err)
		}
		delete(object, "items")
	}

	if raw, found := object["producer"]; found {
		err = json.Unmarshal(raw, &a.Producer)
		if err != nil {
			return fmt.Errorf("error reading 'producer': %w", err)
		}
		delete(object, "producer")
	}

	if raw, found := object["schemaVersion"]; found {
		err = json.Unmarshal(raw, &a.SchemaVersion)
		if err != nil {
			return fmt.Errorf("error reading 'schemaVersion': %w", err)
		}
		delete(object, "schemaVersion")
	}

	if raw, found := object["sentAtMs"]; found {
		err = json.Unmarshal(raw, &a.SentAtMs)
		if err != nil {
			return fmt.Errorf("error reading 'sentAtMs': %w", err)
		}
		delete(object, "sentAtMs")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for IngestBatchRequest to handle AdditionalProperties
func (a IngestBatchRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["batchId"], err = json.Marshal(a.BatchId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'batchId': %w", err)
	}

	if a.Items != nil {
		object["items"], err = json.Marshal(a.Items)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'items': %w", err)
		}
	}

	object["producer"], err = json.Marshal(a.Producer)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'producer': %w", err)
	}

	object["schemaVersion"], err = json.Marshal(a.SchemaVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'schemaVersion': %w", err)
	}

	object["sentAtMs"], err = json.Marshal(a.SentAtMs)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'sentAtMs': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for IngestBatchRequest_Producer. Returns the specified
// element and whether it was found
func (a IngestBatchRequest_Producer) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for IngestBatchRequest_Producer
func (a *IngestBatchRequest_Producer) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for IngestBatchRequest_Producer to handle AdditionalProperties
func (a *IngestBatchRequest_Producer) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["pluginId"]; found {
		err = json.Unmarshal(raw, &a.PluginId)
		if err != nil {
			return fmt.Errorf("error reading 'pluginId': %w", err)
		}
		delete(object, "pluginId")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for IngestBatchRequest_Producer to handle AdditionalProperties
func (a IngestBatchRequest_Producer) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["pluginId"], err = json.Marshal(a.PluginId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'pluginId': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for IngestBatchResponse. Returns the specified
// element and whether it was found
func (a IngestBatchResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for IngestBatchResponse
func (a *IngestBatchResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for IngestBatchResponse to handle AdditionalProperties
func (a *IngestBatchResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["acceptedCount"]; found {
		err = json.Unmarshal(raw, &a.AcceptedCount)
		if err != nil {
			return fmt.Errorf("error reading 'acceptedCount': %w", err)
		}
		delete(object, "acceptedCount")
	}

	if raw, found := object["duplicateCount"]; found {
		err = json.Unmarshal(raw, &a.DuplicateCount)
		if err != nil {
			return fmt.Errorf("error reading 'duplicateCount': %w", err)
		}
		delete(object, "duplicateCount")
	}

	if raw, found := object["persistedCount"]; found {
		err = json.Unmarshal(raw, &a.PersistedCount)
		if err != nil {
			return fmt.Errorf("error reading 'persistedCount': %w", err)
		}
		delete(object, "persistedCount")
	}

	if raw, found := object["rejectedCount"]; found {
		err = json.Unmarshal(raw, &a.RejectedCount)
		if err != nil {
			return fmt.Errorf("error reading 'rejectedCount': %w", err)
		}
		delete(object, "rejectedCount")
	}

	if raw, found := object["rejectedItems"]; found {
		err = json.Unmarshal(raw, &a.RejectedItems)
		if err != nil {
			return fmt.Errorf("error reading 'rejectedItems': %w", err)
		}
		delete(object, "rejectedItems")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for IngestBatchResponse to handle AdditionalProperties
func (a IngestBatchResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["acceptedCount"], err = json.Marshal(a.AcceptedCount)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'acceptedCount': %w", err)
	}

	object["duplicateCount"], err = json.Marshal(a.DuplicateCount)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'duplicateCount': %w", err)
	}

	object["persistedCount"], err = json.Marshal(a.PersistedCount)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'persistedCount': %w", err)
	}

	object["rejectedCount"], err = json.Marshal(a.RejectedCount)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'rejectedCount': %w", err)
	}

	if a.RejectedItems != nil {
		object["rejectedItems"], err = json.Marshal(a.RejectedItems)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'rejectedItems': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for IngestItem. Returns the specified
// element and whether it was found
func (a IngestItem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for IngestItem
func (a *IngestItem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for IngestItem to handle AdditionalProperties
func (a *IngestItem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["data"]; found {
		err = json.Unmarshal(raw, &a.Data)
		if err != nil {
			return fmt.Errorf("error reading 'data': %w", err)
		}
		delete(object, "data")
	}

	if raw, found := object["itemId"]; found {
		err = json.Unmarshal(raw, &a.ItemId)
		if err != nil {
			return fmt.Errorf("error reading 'itemId': %w", err)
		}
		delete(object, "itemId")
	}

	if raw, found := object["kind"]; found {
		err = json.Unmarshal(raw, &a.Kind)
		if err != nil {
			return fmt.Errorf("error reading 'kind': %w", err)
		}
		delete(object, "kind")
	}

	if raw, found := object["occurredAtMs"]; found {
		err = json.Unmarshal(raw, &a.OccurredAtMs)
		if err != nil {
			return fmt.Errorf("error reading 'occurredAtMs': %w", err)
		}
		delete(object, "occurredAtMs")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for IngestItem to handle AdditionalProperties
func (a IngestItem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["data"], err = json.Marshal(a.Data)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'data': %w", err)
	}

	object["itemId"], err = json.Marshal(a.ItemId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'itemId': %w", err)
	}

	object["kind"], err = json.Marshal(a.Kind)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kind': %w", err)
	}

	object["occurredAtMs"], err = json.Marshal(a.OccurredAtMs)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'occurredAtMs': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Page. Returns the specified
// element and whether it was found
func (a Page) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Page
func (a *Page) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Page to handle AdditionalProperties
func (a *Page) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["items"]; found {
		err = json.Unmarshal(raw, &a.Items)
		if err != nil {
			return fmt.Errorf("error reading 'items': %w", err)
		}
		delete(object, "items")
	}

	if raw, found := object["nextCursor"]; found {
		err = json.Unmarshal(raw, &a.NextCursor)
		if err != nil {
			return fmt.Errorf("error reading 'nextCursor': %w", err)
		}
		delete(object, "nextCursor")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Page to handle AdditionalProperties
func (a Page) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Items != nil {
		object["items"], err = json.Marshal(a.Items)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'items': %w", err)
		}
	}

	if a.NextCursor != nil {
		object["nextCursor"], err = json.Marshal(a.NextCursor)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'nextCursor': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List approval records.
	// (GET /lynx/approvals)
	ListApprovals(c *gin.Context, params ListApprovalsParams)
	// Read one approval record.
	// (GET /lynx/approvals/{approvalId})
	GetApproval(c *gin.Context, approvalId string)
	// Resolve one approval record.
	// (POST /lynx/approvals/{approvalId}/resolve)
	ResolveApproval(c *gin.Context, approvalId string)
	// Read dashboard overview metrics.
	// (GET /lynx/dashboard/overview)
	GetDashboardOverview(c *gin.Context, params GetDashboardOverviewParams)
	// List audit events.
	// (GET /lynx/events)
	ListEvents(c *gin.Context, params ListEventsParams)
	// Read one audit event.
	// (GET /lynx/events/{eventId})
	GetEvent(c *gin.Context, eventId string)
	// List approval grant records.
	// (GET /lynx/grants)
	ListGrants(c *gin.Context, params ListGrantsParams)
	// Read one approval grant with execution-chain and related tool-call data.
	// (GET /lynx/grants/{grantId})
	GetGrant(c *gin.Context, grantId string)
	// Read server health.
	// (GET /lynx/health)
	GetHealth(c *gin.Context)
	// Ingest approval upsert items.
	// (POST /lynx/internal/v1/ingest/approvals)
	IngestApprovals(c *gin.Context)
	// Ingest audit event items.
	// (POST /lynx/internal/v1/ingest/audit-events)
	IngestAuditEvents(c *gin.Context)
	// Ingest one plugin event batch.
	// (POST /lynx/internal/v1/ingest/batch)
	IngestBatch(c *gin.Context)
	// Ingest Lynx check upsert items.
	// (POST /lynx/internal/v1/ingest/lynx-checks)
	IngestLynxChecks(c *gin.Context)
	// Ingest session upsert items.
	// (POST /lynx/internal/v1/ingest/sessions)
	IngestSessions(c *gin.Context)
	// Ingest token usage items.
	// (POST /lynx/internal/v1/ingest/token-usage)
	IngestTokenUsage(c *gin.Context)
	// Ingest tool call upsert items.
	// (POST /lynx/internal/v1/ingest/tool-calls)
	IngestToolCalls(c *gin.Context)
	// List Lynx check runs.
	// (GET /lynx/lynx-checks)
	ListLynxChecks(c *gin.Context, params ListLynxChecksParams)
	// Read one Lynx check run.
	// (GET /lynx/lynx-checks/{requestId})
	GetLynxCheck(c *gin.Context, requestId string)
	// Read local console capabilities.
	// (GET /lynx/meta/capabilities)
	GetCapabilities(c *gin.Context)
	// Read policy rules, protected resources, and current policy version.
	// (GET /lynx/policies)
	GetPolicies(c *gin.Context)
	// Create or update one user-managed policy rule.
	// (POST /lynx/policy-rules)
	UpsertPolicyRule(c *gin.Context)
	// Create or update one protected resource policy.
	// (POST /lynx/protected-resources)
	UpsertProtectedResource(c *gin.Context)
	// List conversation sessions.
	// (GET /lynx/sessions)
	ListSessions(c *gin.Context, params ListSessionsParams)
	// Read one conversation session.
	// (GET /lynx/sessions/{sessionKey})
	GetSession(c *gin.Context, sessionKey string)
	// Read token usage summary.
	// (GET /lynx/tokens/summary)
	GetTokenSummary(c *gin.Context, params GetTokenSummaryParams)
	// Read token usage trend.
	// (GET /lynx/tokens/trend)
	GetTokenTrend(c *gin.Context, params GetTokenTrendParams)
	// List token usage records.
	// (GET /lynx/tokens/usage)
	ListTokenUsage(c *gin.Context, params ListTokenUsageParams)
	// List tool calls.
	// (GET /lynx/tool-calls)
	ListToolCalls(c *gin.Context, params ListToolCallsParams)
	// Read one tool call.
	// (GET /lynx/tool-calls/{toolCallId})
	GetToolCall(c *gin.Context, toolCallId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListApprovals operation middleware
func (siw *ServerInterfaceWrapper) ListApprovals(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListApprovalsParams

	// ------------- Optional query parameter "fromMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "fromMs", c.Request.URL.Query(), &params.FromMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fromMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "toMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "toMs", c.Request.URL.Query(), &params.ToMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter toMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sessionKey" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sessionKey", c.Request.URL.Query(), &params.SessionKey, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionKey: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "runId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "runId", c.Request.URL.Query(), &params.RunId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter runId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "riskLevel" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "riskLevel", c.Request.URL.Query(), &params.RiskLevel, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter riskLevel: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "resolution" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "resolution", c.Request.URL.Query(), &params.Resolution, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter resolution: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "toolName" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "toolName", c.Request.URL.Query(), &params.ToolName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter toolName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "module" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "module", c.Request.URL.Query(), &params.Module, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter module: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "scopeType" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "scopeType", c.Request.URL.Query(), &params.ScopeType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scopeType: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "requesterOuId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "requesterOuId", c.Request.URL.Query(), &params.RequesterOuId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter requesterOuId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApprovals(c, params)
}

// GetApproval operation middleware
func (siw *ServerInterfaceWrapper) GetApproval(c *gin.Context) {

	var err error

	// ------------- Path parameter "approvalId" -------------
	var approvalId string

	err = runtime.BindStyledParameterWithOptions("simple", "approvalId", c.Param("approvalId"), &approvalId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter approvalId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApproval(c, approvalId)
}

// ResolveApproval operation middleware
func (siw *ServerInterfaceWrapper) ResolveApproval(c *gin.Context) {

	var err error

	// ------------- Path parameter "approvalId" -------------
	var approvalId string

	err = runtime.BindStyledParameterWithOptions("simple", "approvalId", c.Param("approvalId"), &approvalId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter approvalId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResolveApproval(c, approvalId)
}

// GetDashboardOverview operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardOverview(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardOverviewParams

	// ------------- Optional query parameter "fromMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "fromMs", c.Request.URL.Query(), &params.FromMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fromMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "toMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "toMs", c.Request.URL.Query(), &params.ToMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter toMs: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDashboardOverview(c, params)
}

// ListEvents operation middleware
func (siw *ServerInterfaceWrapper) ListEvents(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", c.Request.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "fromMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "fromMs", c.Request.URL.Query(), &params.FromMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fromMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "toMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "toMs", c.Request.URL.Query(), &params.ToMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter toMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sessionKey" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sessionKey", c.Request.URL.Query(), &params.SessionKey, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionKey: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "runId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "runId", c.Request.URL.Query(), &params.RunId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter runId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "riskLevel" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "riskLevel", c.Request.URL.Query(), &params.RiskLevel, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter riskLevel: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "enforcementAction" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "enforcementAction", c.Request.URL.Query(), &params.EnforcementAction, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter enforcementAction: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "hookName" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "hookName", c.Request.URL.Query(), &params.HookName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter hookName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "eventType" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "eventType", c.Request.URL.Query(), &params.EventType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter eventType: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", c.Request.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter category: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "subCategory" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "subCategory", c.Request.URL.Query(), &params.SubCategory, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter subCategory: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "direction" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "direction", c.Request.URL.Query(), &params.Direction, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter direction: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "primaryModule" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "primaryModule", c.Request.URL.Query(), &params.PrimaryModule, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter primaryModule: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "requestId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "requestId", c.Request.URL.Query(), &params.RequestId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter requestId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "toolCallId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "toolCallId", c.Request.URL.Query(), &params.ToolCallId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter toolCallId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "approvalId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "approvalId", c.Request.URL.Query(), &params.ApprovalId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter approvalId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "includeRoutineHeartbeat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "includeRoutineHeartbeat", c.Request.URL.Query(), &params.IncludeRoutineHeartbeat, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeRoutineHeartbeat: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListEvents(c, params)
}

// GetEvent operation middleware
func (siw *ServerInterfaceWrapper) GetEvent(c *gin.Context) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId string

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", c.Param("eventId"), &eventId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter eventId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetEvent(c, eventId)
}

// ListGrants operation middleware
func (siw *ServerInterfaceWrapper) ListGrants(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGrantsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", c.Request.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "chainId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "chainId", c.Request.URL.Query(), &params.ChainId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter chainId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "requesterId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "requesterId", c.Request.URL.Query(), &params.RequesterId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter requesterId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "revoked" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "revoked", c.Request.URL.Query(), &params.Revoked, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter revoked: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageNum" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageNum", c.Request.URL.Query(), &params.PageNum, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageNum: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGrants(c, params)
}

// GetGrant operation middleware
func (siw *ServerInterfaceWrapper) GetGrant(c *gin.Context) {

	var err error

	// ------------- Path parameter "grantId" -------------
	var grantId string

	err = runtime.BindStyledParameterWithOptions("simple", "grantId", c.Param("grantId"), &grantId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter grantId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGrant(c, grantId)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// IngestApprovals operation middleware
func (siw *ServerInterfaceWrapper) IngestApprovals(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.IngestApprovals(c)
}

// IngestAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) IngestAuditEvents(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.IngestAuditEvents(c)
}

// IngestBatch operation middleware
func (siw *ServerInterfaceWrapper) IngestBatch(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.IngestBatch(c)
}

// IngestLynxChecks operation middleware
func (siw *ServerInterfaceWrapper) IngestLynxChecks(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.IngestLynxChecks(c)
}

// IngestSessions operation middleware
func (siw *ServerInterfaceWrapper) IngestSessions(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.IngestSessions(c)
}

// IngestTokenUsage operation middleware
func (siw *ServerInterfaceWrapper) IngestTokenUsage(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.IngestTokenUsage(c)
}

// IngestToolCalls operation middleware
func (siw *ServerInterfaceWrapper) IngestToolCalls(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.IngestToolCalls(c)
}

// ListLynxChecks operation middleware
func (siw *ServerInterfaceWrapper) ListLynxChecks(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLynxChecksParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", c.Request.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "fromMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "fromMs", c.Request.URL.Query(), &params.FromMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fromMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "toMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "toMs", c.Request.URL.Query(), &params.ToMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter toMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sessionKey" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sessionKey", c.Request.URL.Query(), &params.SessionKey, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionKey: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", c.Request.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter source: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "trigger" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "trigger", c.Request.URL.Query(), &params.Trigger, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trigger: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "messageProvider" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "messageProvider", c.Request.URL.Query(), &params.MessageProvider, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter messageProvider: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLynxChecks(c, params)
}

// GetLynxCheck operation middleware
func (siw *ServerInterfaceWrapper) GetLynxCheck(c *gin.Context) {

	var err error

	// ------------- Path parameter "requestId" -------------
	var requestId string

	err = runtime.BindStyledParameterWithOptions("simple", "requestId", c.Param("requestId"), &requestId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter requestId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLynxCheck(c, requestId)
}

// GetCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCapabilities(c)
}

// GetPolicies operation middleware
func (siw *ServerInterfaceWrapper) GetPolicies(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPolicies(c)
}

// UpsertPolicyRule operation middleware
func (siw *ServerInterfaceWrapper) UpsertPolicyRule(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpsertPolicyRule(c)
}

// UpsertProtectedResource operation middleware
func (siw *ServerInterfaceWrapper) UpsertProtectedResource(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpsertProtectedResource(c)
}

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSessionsParams

	// ------------- Optional query parameter "fromMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "fromMs", c.Request.URL.Query(), &params.FromMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fromMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "toMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "toMs", c.Request.URL.Query(), &params.ToMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter toMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "channelProfile" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "channelProfile", c.Request.URL.Query(), &params.ChannelProfile, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter channelProfile: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "channelId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "channelId", c.Request.URL.Query(), &params.ChannelId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter channelId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "requesterId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "requesterId", c.Request.URL.Query(), &params.RequesterId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter requesterId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "requesterOuId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "requesterOuId", c.Request.URL.Query(), &params.RequesterOuId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter requesterOuId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "isGroup" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "isGroup", c.Request.URL.Query(), &params.IsGroup, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter isGroup: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSessions(c, params)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(c *gin.Context) {

	var err error

	// ------------- Path parameter "sessionKey" -------------
	var sessionKey string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionKey", c.Param("sessionKey"), &sessionKey, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionKey: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSession(c, sessionKey)
}

// GetTokenSummary operation middleware
func (siw *ServerInterfaceWrapper) GetTokenSummary(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTokenSummaryParams

	// ------------- Optional query parameter "fromMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "fromMs", c.Request.URL.Query(), &params.FromMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fromMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "toMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "toMs", c.Request.URL.Query(), &params.ToMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter toMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sessionKey" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sessionKey", c.Request.URL.Query(), &params.SessionKey, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionKey: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "runId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "runId", c.Request.URL.Query(), &params.RunId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter runId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "provider" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "provider", c.Request.URL.Query(), &params.Provider, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "model" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "model", c.Request.URL.Query(), &params.Model, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter model: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTokenSummary(c, params)
}

// GetTokenTrend operation middleware
func (siw *ServerInterfaceWrapper) GetTokenTrend(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTokenTrendParams

	// ------------- Optional query parameter "fromMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "fromMs", c.Request.URL.Query(), &params.FromMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fromMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "toMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "toMs", c.Request.URL.Query(), &params.ToMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter toMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sessionKey" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sessionKey", c.Request.URL.Query(), &params.SessionKey, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionKey: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "runId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "runId", c.Request.URL.Query(), &params.RunId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter runId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "provider" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "provider", c.Request.URL.Query(), &params.Provider, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "model" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "model", c.Request.URL.Query(), &params.Model, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter model: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "bucket" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "bucket", c.Request.URL.Query(), &params.Bucket, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bucket: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTokenTrend(c, params)
}

// ListTokenUsage operation middleware
func (siw *ServerInterfaceWrapper) ListTokenUsage(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTokenUsageParams

	// ------------- Optional query parameter "fromMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "fromMs", c.Request.URL.Query(), &params.FromMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fromMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "toMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "toMs", c.Request.URL.Query(), &params.ToMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter toMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sessionKey" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sessionKey", c.Request.URL.Query(), &params.SessionKey, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionKey: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "runId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "runId", c.Request.URL.Query(), &params.RunId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter runId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "provider" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "provider", c.Request.URL.Query(), &params.Provider, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "model" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "model", c.Request.URL.Query(), &params.Model, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter model: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "agentId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "agentId", c.Request.URL.Query(), &params.AgentId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter agentId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "isEstimated" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "isEstimated", c.Request.URL.Query(), &params.IsEstimated, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter isEstimated: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTokenUsage(c, params)
}

// ListToolCalls operation middleware
func (siw *ServerInterfaceWrapper) ListToolCalls(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListToolCallsParams

	// ------------- Optional query parameter "fromMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "fromMs", c.Request.URL.Query(), &params.FromMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fromMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "toMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "toMs", c.Request.URL.Query(), &params.ToMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter toMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sessionKey" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sessionKey", c.Request.URL.Query(), &params.SessionKey, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionKey: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "runId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "runId", c.Request.URL.Query(), &params.RunId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter runId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "riskLevel" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "riskLevel", c.Request.URL.Query(), &params.RiskLevel, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter riskLevel: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "enforcementAction" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "enforcementAction", c.Request.URL.Query(), &params.EnforcementAction, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter enforcementAction: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "toolName" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "toolName", c.Request.URL.Query(), &params.ToolName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter toolName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "resultStatus" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "resultStatus", c.Request.URL.Query(), &params.ResultStatus, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter resultStatus: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "approvalId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "approvalId", c.Request.URL.Query(), &params.ApprovalId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter approvalId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListToolCalls(c, params)
}

// GetToolCall operation middleware
func (siw *ServerInterfaceWrapper) GetToolCall(c *gin.Context) {

	var err error

	// ------------- Path parameter "toolCallId" -------------
	var toolCallId string

	err = runtime.BindStyledParameterWithOptions("simple", "toolCallId", c.Param("toolCallId"), &toolCallId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter toolCallId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetToolCall(c, toolCallId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/lynx/approvals", wrapper.ListApprovals)
	router.GET(options.BaseURL+"/lynx/approvals/:approvalId", wrapper.GetApproval)
	router.POST(options.BaseURL+"/lynx/approvals/:approvalId/resolve", wrapper.ResolveApproval)
	router.GET(options.BaseURL+"/lynx/dashboard/overview", wrapper.GetDashboardOverview)
	router.GET(options.BaseURL+"/lynx/events", wrapper.ListEvents)
	router.GET(options.BaseURL+"/lynx/events/:eventId", wrapper.GetEvent)
	router.GET(options.BaseURL+"/lynx/grants", wrapper.ListGrants)
	router.GET(options.BaseURL+"/lynx/grants/:grantId", wrapper.GetGrant)
	router.GET(options.BaseURL+"/lynx/health", wrapper.GetHealth)
	router.POST(options.BaseURL+"/lynx/internal/v1/ingest/approvals", wrapper.IngestApprovals)
	router.POST(options.BaseURL+"/lynx/internal/v1/ingest/audit-events", wrapper.IngestAuditEvents)
	router.POST(options.BaseURL+"/lynx/internal/v1/ingest/batch", wrapper.IngestBatch)
	router.POST(options.BaseURL+"/lynx/internal/v1/ingest/lynx-checks", wrapper.IngestLynxChecks)
	router.POST(options.BaseURL+"/lynx/internal/v1/ingest/sessions", wrapper.IngestSessions)
	router.POST(options.BaseURL+"/lynx/internal/v1/ingest/token-usage", wrapper.IngestTokenUsage)
	router.POST(options.BaseURL+"/lynx/internal/v1/ingest/tool-calls", wrapper.IngestToolCalls)
	router.GET(options.BaseURL+"/lynx/lynx-checks", wrapper.ListLynxChecks)
	router.GET(options.BaseURL+"/lynx/lynx-checks/:requestId", wrapper.GetLynxCheck)
	router.GET(options.BaseURL+"/lynx/meta/capabilities", wrapper.GetCapabilities)
	router.GET(options.BaseURL+"/lynx/policies", wrapper.GetPolicies)
	router.POST(options.BaseURL+"/lynx/policy-rules", wrapper.UpsertPolicyRule)
	router.POST(options.BaseURL+"/lynx/protected-resources", wrapper.UpsertProtectedResource)
	router.GET(options.BaseURL+"/lynx/sessions", wrapper.ListSessions)
	router.GET(options.BaseURL+"/lynx/sessions/:sessionKey", wrapper.GetSession)
	router.GET(options.BaseURL+"/lynx/tokens/summary", wrapper.GetTokenSummary)
	router.GET(options.BaseURL+"/lynx/tokens/trend", wrapper.GetTokenTrend)
	router.GET(options.BaseURL+"/lynx/tokens/usage", wrapper.ListTokenUsage)
	router.GET(options.BaseURL+"/lynx/tool-calls", wrapper.ListToolCalls)
	router.GET(options.BaseURL+"/lynx/tool-calls/:toolCallId", wrapper.GetToolCall)
}
